/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_fmi_jnifmuapi_NativeFmu_ICallback */

#ifndef _Included_org_intocps_fmi_jnifmuapi_NativeFmu_ICallback
#define _Included_org_intocps_fmi_jnifmuapi_NativeFmu_ICallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
