/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_fmi3_jnifmuapi_NativeFmu3 */

#ifndef _Included_org_intocps_fmi3_jnifmuapi_NativeFmu3
#define _Included_org_intocps_fmi3_jnifmuapi_NativeFmu3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    nGetVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_nGetVersion
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    nInstantiateModelExchange
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZJLorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackLogMessage;)J
 */
JNIEXPORT jlong JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_nInstantiateModelExchange
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jboolean, jboolean, jlong, jobject);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    nInstantiateCoSimulation
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZZ[JJJLorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackLogMessage;Lorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackIntermediateUpdate;)J
 */
JNIEXPORT jlong JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_nInstantiateCoSimulation
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jboolean, jboolean, jboolean, jboolean, jlongArray, jlong, jlong, jobject, jobject);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    n3InstantiateScheduledExecution
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ[JJJLorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackLogMessage;Lorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackIntermediateUpdate;Lorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackLockPreemption;Lorg/intocps/fmi3/jnifmuapi/NativeFmu3/ICallbackUnlockPreemption;)J
 */
JNIEXPORT jlong JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_n3InstantiateScheduledExecution
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jboolean, jboolean, jlongArray, jlong, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    nLoadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_nLoadLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    nUnLoad
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_nUnLoad
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_intocps_fmi3_jnifmuapi_NativeFmu3
 * Method:    getJniApiVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_intocps_fmi3_jnifmuapi_NativeFmu3_getJniApiVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
