/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance */

#ifndef _Included_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
#define _Included_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetDebugLogging
 * Signature: (JJZ[Ljava/lang/String;)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetDebugLogging
  (JNIEnv *, jobject, jlong, jlong, jboolean, jobjectArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nFreeInstance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nFreeInstance
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nEnterInitializationMode
 * Signature: (JJZDDZD)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nEnterInitializationMode
  (JNIEnv *, jobject, jlong, jlong, jboolean, jdouble, jdouble, jboolean, jdouble);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nExitInitializationMode
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nExitInitializationMode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nEnterEventMode
 * Signature: (JJZZ[IIZ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nEnterEventMode
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean, jintArray, jint, jboolean);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nTerminate
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nTerminate
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nReset
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nReset
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetFloat32
 * Signature: (J[JI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetFloat32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetFloat64
 * Signature: (J[JI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetFloat64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetInt8
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetInt8
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetUInt8
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetUInt8
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetInt16
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetInt16
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetUInt16
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetUInt16
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetInt32
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetInt32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetUInt32
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetUInt32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetInt64
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetInt64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetUInt64
 * Signature: (J[JI[JI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetUInt64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jlongArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetBoolean
 * Signature: (J[JI[ZI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetBoolean
  (JNIEnv *, jobject, jlong, jlongArray, jint, jbooleanArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetString
 * Signature: (J[JI[Ljava/lang/String;I)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetString
  (JNIEnv *, jobject, jlong, jlongArray, jint, jobjectArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetBinary
 * Signature: (J[JI[J[BI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetBinary
  (JNIEnv *, jobject, jlong, jlongArray, jint, jlongArray, jbyteArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetFloat32
 * Signature: (J[JI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetFloat32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetFloat64
 * Signature: (J[JI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetFloat64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetInt8
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetInt8
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetUInt8
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetUInt8
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetInt16
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetInt16
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetUInt16
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetUInt16
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetInt32
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetInt32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetUInt32
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetUInt32
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetInt64
 * Signature: (J[JI[II)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetInt64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jintArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetUInt64
 * Signature: (J[JI[JI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetUInt64
  (JNIEnv *, jobject, jlong, jlongArray, jint, jlongArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetBoolean
 * Signature: (J[JI[ZI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetBoolean
  (JNIEnv *, jobject, jlong, jlongArray, jint, jbooleanArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetString
 * Signature: (J[JI[Ljava/lang/String;I)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetString
  (JNIEnv *, jobject, jlong, jlongArray, jint, jobjectArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetBinary
 * Signature: (J[JI[J[[BI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetBinary
  (JNIEnv *, jobject, jlong, jlongArray, jint, jlongArray, jobjectArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetNumberOfVariableDependencies
 * Signature: (JJ[J)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetNumberOfVariableDependencies
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetVariableDependencies
 * Signature: (JJJ[J[J[J[Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3DependencyKind;I)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetVariableDependencies
  (JNIEnv *, jobject, jlong, jlong, jlong, jlongArray, jlongArray, jlongArray, jobjectArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetFMUState
 * Signature: (JJ[J)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetFMUState
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetFMUState
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetFMUState
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nFreeFMUState
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nFreeFMUState
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSerializedFMUStateSize
 * Signature: (JJJ[J)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSerializedFMUStateSize
  (JNIEnv *, jobject, jlong, jlong, jlong, jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetDirectionalDerivative
 * Signature: (JJ[JI[JI[DI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetDirectionalDerivative
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jlongArray, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetAdjointDerivative
 * Signature: (JJ[JI[JI[DI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetAdjointDerivative
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jlongArray, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nEnterConfigurationMode
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nEnterConfigurationMode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nExitConfigurationMode
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nExitConfigurationMode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetClock
 * Signature: (JJ[JI[ZI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetClock
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jbooleanArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetClock
 * Signature: (JJ[JI[ZI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetClock
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jbooleanArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetIntervalDecimal
 * Signature: (JJ[JI[D[Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3IntervalQualifier;I)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetIntervalDecimal
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jdoubleArray, jobjectArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetIntervalFraction
 * Signature: (JJ[JI[J[JI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetIntervalFraction
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jlongArray, jlongArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetIntervalDecimal
 * Signature: (JJ[JI[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetIntervalDecimal
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetIntervalFraction
 * Signature: (JJ[JI[J[JI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetIntervalFraction
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jlongArray, jlongArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nUpdateDiscreteStates
 * Signature: (JJ[Z[Z[Z[Z[Z[D)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nUpdateDiscreteStates
  (JNIEnv *, jobject, jlong, jlong, jbooleanArray, jbooleanArray, jbooleanArray, jbooleanArray, jbooleanArray, jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nEnterContinuousTimeMode
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nEnterContinuousTimeMode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nCompletedIntegratorStep
 * Signature: (JJZ[Z[Z)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nCompletedIntegratorStep
  (JNIEnv *, jobject, jlong, jlong, jboolean, jbooleanArray, jbooleanArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetTime
 * Signature: (JJD)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetTime
  (JNIEnv *, jobject, jlong, jlong, jdouble);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nSetContinuousStates
 * Signature: (JJ[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nSetContinuousStates
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetDerivatives
 * Signature: (J[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetDerivatives
  (JNIEnv *, jobject, jlong, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetEventIndicators
 * Signature: (JJ[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetEventIndicators
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetContinuousStates
 * Signature: (JJ[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetContinuousStates
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetNominalsOfContinuousStates
 * Signature: (JJ[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetNominalsOfContinuousStates
  (JNIEnv *, jobject, jlong, jlong, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetNumberOfEventIndicators
 * Signature: (JJ[J)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetNumberOfEventIndicators
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetNumberOfContinuousStates
 * Signature: (JJ[J)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetNumberOfContinuousStates
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nEnterStepMode
 * Signature: (JJ)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nEnterStepMode
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nGetOutputDerivatives
 * Signature: (JJ[JI[I[DI)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nGetOutputDerivatives
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jint, jintArray, jdoubleArray, jint);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nDoStep
 * Signature: (JJDDZ[Z[Z[Z[D)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nDoStep
  (JNIEnv *, jobject, jlong, jlong, jdouble, jdouble, jboolean, jbooleanArray, jbooleanArray, jbooleanArray, jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance
 * Method:    nActivateModelPartition
 * Signature: (JJJID)Lorg/intocps/fmi/jnifmuapi/fmi3/Fmi3Status;
 */
JNIEXPORT jobject JNICALL Java_org_intocps_fmi_jnifmuapi_fmi3_NativeFmu3Instance_nActivateModelPartition
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
