/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_fmi_jnifmuapi_NativeFmuComponent */

#ifndef _Included_org_intocps_fmi_jnifmuapi_NativeFmuComponent
#define _Included_org_intocps_fmi_jnifmuapi_NativeFmuComponent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetDebugLogging
 * Signature: (JJZ[Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetDebugLogging(
    JNIEnv *, jobject, jlong, jlong, jboolean, jobjectArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nFreeInstance
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nFreeInstance(JNIEnv *,
                                                                jobject, jlong,
                                                                jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetupExperiment
 * Signature: (JJZDDZD)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetupExperiment(
    JNIEnv *, jobject, jlong, jlong, jboolean, jdouble, jdouble, jboolean,
    jdouble);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nEnterInitializationMode
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nEnterInitializationMode(
    JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nExitInitializationMode
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nExitInitializationMode(
    JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nTerminate
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nTerminate(JNIEnv *, jobject,
                                                             jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nReset
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nReset(JNIEnv *, jobject,
                                                         jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetReal
 * Signature: (JJ[JJ[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetReal(JNIEnv *, jobject,
                                                           jlong, jlong,
                                                           jlongArray, jlong,
                                                           jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetInteger
 * Signature: (JJ[JJ[I)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetInteger(JNIEnv *, jobject,
                                                              jlong, jlong,
                                                              jlongArray, jlong,
                                                              jintArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetBoolean
 * Signature: (JJ[JJ[Z)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetBoolean(JNIEnv *, jobject,
                                                              jlong, jlong,
                                                              jlongArray, jlong,
                                                              jbooleanArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetString
 * Signature: (JJ[JJ[Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetString(JNIEnv *, jobject,
                                                             jlong, jlong,
                                                             jlongArray, jlong,
                                                             jobjectArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetReal
 * Signature: (JJ[JJ[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetReal(JNIEnv *, jobject,
                                                           jlong, jlong,
                                                           jlongArray, jlong,
                                                           jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetInteger
 * Signature: (JJ[JJ[I)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetInteger(JNIEnv *, jobject,
                                                              jlong, jlong,
                                                              jlongArray, jlong,
                                                              jintArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetBoolean
 * Signature: (JJ[JJ[Z)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetBoolean(JNIEnv *, jobject,
                                                              jlong, jlong,
                                                              jlongArray, jlong,
                                                              jbooleanArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetString
 * Signature: (JJ[JJ[Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetString(JNIEnv *, jobject,
                                                             jlong, jlong,
                                                             jlongArray, jlong,
                                                             jobjectArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetFmuState
 * Signature: (JJ[J)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetFmuState(JNIEnv *,
                                                               jobject, jlong,
                                                               jlong,
                                                               jlongArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetFmuState
 * Signature: (JJJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetFmuState(JNIEnv *,
                                                               jobject, jlong,
                                                               jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nFreeFmuState
 * Signature: (JJJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nFreeFmuState(JNIEnv *,
                                                                jobject, jlong,
                                                                jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetDirectionalDerivative
 * Signature: (JJ[JJ[JJ[D[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetDirectionalDerivative(
    JNIEnv *, jobject, jlong, jlong, jlongArray, jlong, jlongArray, jlong,
    jdoubleArray, jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nSetRealInputDerivatives
 * Signature: (JJ[JJ[I[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nSetRealInputDerivatives(
    JNIEnv *, jobject, jlong, jlong, jlongArray, jlong, jintArray,
    jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetRealOutputDerivatives
 * Signature: (JJ[JJ[I[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetRealOutputDerivatives(
    JNIEnv *, jobject, jlong, jlong, jlongArray, jlong, jintArray,
    jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nDoStep
 * Signature: (JJDDZ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nDoStep(JNIEnv *, jobject,
                                                          jlong, jlong, jdouble,
                                                          jdouble, jboolean);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nCancelStep
 * Signature: (JJ)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nCancelStep(JNIEnv *, jobject,
                                                              jlong, jlong);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetStatus
 * Signature: (JJB[B)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetStatus(JNIEnv *, jobject,
                                                             jlong, jlong,
                                                             jbyte, jbyteArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetRealStatus
 * Signature: (JJB[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetRealStatus(JNIEnv *,
                                                                 jobject, jlong,
                                                                 jlong, jbyte,
                                                                 jdoubleArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetIntegerStatus
 * Signature: (JJB[I)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetIntegerStatus(
    JNIEnv *, jobject, jlong, jlong, jbyte, jintArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetBooleanStatus
 * Signature: (JJB[Z)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetBooleanStatus(
    JNIEnv *, jobject, jlong, jlong, jbyte, jbooleanArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetStringStatus
 * Signature: (JJB[Ljava/lang/String;)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetStringStatus(
    JNIEnv *, jobject, jlong, jlong, jbyte, jobjectArray);

/*
 * Class:     org_intocps_fmi_jnifmuapi_NativeFmuComponent
 * Method:    nGetMaxStepsize
 * Signature: (JJ[D)B
 */
JNIEXPORT jbyte JNICALL
Java_org_intocps_fmi_jnifmuapi_NativeFmuComponent_nGetMaxStepsize(JNIEnv *,
                                                                  jobject,
                                                                  jlong, jlong,
                                                                  jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
