/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_intocps_fmi3_jnifmuapi_NativeFmu3_ICallbackUnlockPreemption */

#ifndef _Included_org_intocps_fmi3_jnifmuapi_NativeFmu3_ICallbackUnlockPreemption
#define _Included_org_intocps_fmi3_jnifmuapi_NativeFmu3_ICallbackUnlockPreemption
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
