# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Change log test

on:
  workflow_dispatch:
#    inputs:
#      releaseversion:
#        description: 'Release version'
#        required: true
#        default: '2.4.0'
#      snapshotversion:
#        description: 'Next snapshot version'
#        required: true
#        default: '2.4.1'

env:
  JAVA_VERSION: 1.8
  SERVER_ID: ossrh
  PYTHON_VERSION: '3.9.9'



jobs:
  
  
  final:
    name: Build and Deploy Combined Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Create changelog config
        run: echo '{"max_back_track_time_days":1095}' > configuration.json

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        with:
          configuration: "configuration.json"
          toTag: development
          fromTag: Release/1.0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate changelog
        run: echo "${{ steps.changelog.outputs.changelog }}"

